"""
AetherForge True Agent Tool Calling (ReAct Loop)
===============================================
Proves a standard OpenAI-compatible agent can dynamically discover
the AetherForge VRAM optimization tool, reason about a task, and
execute the hardware swap autonomously.
"""

import requests
import json
from openai import OpenAI

# AetherForge Configuration Link
from src.config import settings

# Dynamically construct API URL from the single source of truth
AETHERFORGE_URL = f"http://{settings.api_host}:{settings.api_port}"

client = OpenAI(
    api_key="sk-local-test-key", 
)

def fetch_aetherforge_tools():
    """Dynamically fetches the live schema from the AetherForge control plane."""
    try:
        response = requests.get(f"{AETHERFORGE_URL}/system/tools")
        response.raise_for_status()
        return [response.json()]
    except Exception as e:
        print(f"[!] Failed to fetch tool schema from AetherForge: {e}")
        return []

def execute_tool_call(tool_name, arguments):
    """Routes the LLM's physical hardware request back to the AetherForge API."""
    if tool_name == "aetherforge_optimize_vram":
        print(f"\n⚡ [System] Firing Fast-Swap via AetherForge: {arguments['mode'].upper()}")
        response = requests.post(
            f"{AETHERFORGE_URL}/system/strategy", 
            json=arguments
        )
        return response.json()
    return {"error": "Unknown tool"}

def run_agent_loop(user_prompt: str):
    print(f"\n👤 [User Request]: {user_prompt}")
    
    # 1. Discover the tool schema from AetherForge
    tools = fetch_aetherforge_tools()
    if not tools:
        return
        
    messages = [
        {
            "role": "system", 
            "content": (
                "You are an autonomous AI engineering assistant running on local hardware. "
                "You have access to a hypervisor tool that manages your own physical VRAM layers. "
                "If a task requires heavy coding, deep reasoning, or complex generation, ALWAYS call "
                "the `aetherforge_optimize_vram` tool with 'high_fidelity' BEFORE you begin answering. "
                "For simple chat, use 'balanced'."
            )
        },
        {"role": "user", "content": user_prompt}
    ]

    print("\n🤖 [Agent] Reasoning about the task...")
    
    # 2. First LLM Call: The agent evaluates the prompt against the tool schema
    response = client.chat.completions.create(
        model="gpt-4o-mini", # Replace with your local model name if needed
        messages=messages,
        tools=tools,
        tool_choice="auto"
    )
    
    message = response.choices[0].message

    # 3. Handle Tool Calls (The ReAct Loop)
    if message.tool_calls:
        for tool_call in message.tool_calls:
            print(f"\n🛠️ [Agent Action] Decided to call tool: {tool_call.function.name}")
            
            # Parse the parameters hallucinated/generated by the LLM
            arguments = json.loads(tool_call.function.arguments)
            print(f"   -> LLM generated payload: {json.dumps(arguments, indent=2)}")
            
            # 4. Execute the hardware swap against AetherForge
            tool_result = execute_tool_call(tool_call.function.name, arguments)
            print(f"   -> AetherForge response: {json.dumps(tool_result, indent=2)}")
            
            # 5. Provide the hardware execution result back to the LLM
            messages.append(message) 
            messages.append({
                "role": "tool",
                "tool_call_id": tool_call.id,
                "name": tool_call.function.name,
                "content": json.dumps(tool_result)
            })
            
            print("\n🤖 [Agent] Hardware optimized. Generating final response...")
            final_response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=messages
            )
            print(f"\n🤖 [Agent Final Answer]:\n{final_response.choices[0].message.content}")
            
    else:
        print(f"\n🤖 [Agent] (No tool used) Answer:\n{message.content}")

if __name__ == "__main__":
    # Test: A heavy coding task that should force the LLM to trigger a high_fidelity Fast-Swap
    complex_prompt = (
        "I need you to write a multi-threaded Python web scraper using Playwright "
        "that bypasses Cloudflare and extracts JSON data into a Postgres database."
    )
    run_agent_loop(complex_prompt)