"""
AetherForge Tensor Bridge Interface
===================================
Defines the strict data contracts and abstract base classes required for 
communication between the predictive Cache Manager and the Hardware Engine.
"""

import abc
from dataclasses import dataclass, field
from typing import List, Dict, Set, Tuple

@dataclass(frozen=True)
class MemoryInstruction:
    """
    A deterministic memory operation payload generated by the Cache Manager.
    The Hardware Engine consumes this to execute physical memory swaps.
    """
    layer_index: int
    load_experts: Set[int] = field(default_factory=set)    # Experts to move from RAM -> VRAM
    evict_experts: Set[int] = field(default_factory=set)   # Experts to drop from VRAM -> RAM
    retain_experts: Set[int] = field(default_factory=set)  # Experts locked in VRAM

    def is_noop(self) -> bool:
        """Returns True if no physical memory movement is required."""
        return not self.load_experts and not self.evict_experts

@dataclass
class TokenRoutingState:
    """
    The mathematical state of a token passing through a single MoE layer.
    """
    token_id: int
    layer_index: int
    routing_probabilities: Dict[int, float]  # mapping of expert_id to activation probability

class ITensorBridge(abc.ABC):
    """
    Abstract Base Class defining the required hardware hooks.
    Any inference engine (llama.cpp, vLLM, MLX) must implement these methods
    to act as the 'Muscle' for the AetherForge hypervisor.
    """

    @abc.abstractmethod
    def intercept_logits(self) -> TokenRoutingState:
        """
        Hook into the engine's forward pass to extract the router's probabilities
        BEFORE the token is fully calculated.
        """
        pass

    @abc.abstractmethod
    def execute_memory_instruction(self, instruction: MemoryInstruction) -> bool:
        """
        Forces the hardware engine to physically move weight tensors between
        System RAM and GPU VRAM based on the provided instruction.
        
        Args:
            instruction (MemoryInstruction): The deterministic commands from the Brain.
            
        Returns:
            bool: True if the hardware successfully executed the swap, False if it failed.
        """
        pass

    @abc.abstractmethod
    def get_hardware_metrics(self) -> Dict[str, float]:
        """
        Returns live telemetry from the GPU (current VRAM used, temperature, bandwidth).
        """
        pass